import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{display:"flex", flexDirection:"column", height:"100vh"}}>
          <header style={{height:"200px", backgroundColor:"red", width:"100%"}}> Header</header>
          {children}
          <footer style={{height:"200px", backgroundColor:"blue", width:"100%"}}> Footer </footer>
        </div>
      </body>
    </html>
  );
}
